name: surf_flutter_cources
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  spider: ^4.2.2
  intl: ^0.19.0
  bottom_sheet: ^4.0.4
  decimal: ^3.0.2
  collection: ^1.18.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1

dev_dependencies:
#  build_runner: ^2.3.3
#  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/task-3/
    - assets/json/
    - assets/images/task-2-1/





