name: surf_flutter_cources
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/task-2/

